version: 2.1


orbs:
  browser-tools: circleci/browser-tools@1.4.0

commands: 
  install-tar: 
    steps:
    - run: 
          name : install taz
          command: |
            sudo wget -c http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz -O - | sudo tar -xz -C /etc/nginx/

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          google-chrome --version
      - run: mvn dependency:go-offline # gets the project dependencies 
      - run: mvn package -Dmaven.test.skip=true
  test : 
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: yum -y install tar gzip
      - run:
          google-chrome --version
      - run: mvn dependency:go-offline # gets the project dependencies 
      - run: mvn test
      - run:
          name: Creating Test Artifacts
          command: |
            tar -czvf target.tar.gz target;
            mkdir /tmp/artifacts;
            cp  target.tar.gz /tmp/artifacts;

      - store_artifacts:
          path: /tmp/artifacts


workflows:
  buildmvn:
    jobs:
      - build
      - test:
          requires : 
              - build
