version: 2.1


orbs:
  browser-tools: circleci/browser-tools@1.4.4

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn dependency:go-offline # gets the project dependencies 
      - run: mvn package -Dmaven.test.skip=true
  test : 
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          google-chrome --version
          chromedriver --version
      - run: mvn dependency:go-offline # gets the project dependencies 
      - run: mvn test
      - run: tar cvzf target.tgz target
      - store_artifacts:
          path:  target

workflows:
  buildmvn:
    jobs:
      - build
      - test:
          requires : 
              - build
